#ifndef SECURE_INPUT_TYPES_H
#define SECURE_INPUT_TYPES_H

typedef enum
{
    SECURE_INPUT_EVENT_NONE = 0,

    SECURE_INPUT_EVENT_UP,
    SECURE_INPUT_EVENT_DOWN,
    SECURE_INPUT_EVENT_LEFT,
    SECURE_INPUT_EVENT_RIGHT,

    SECURE_INPUT_EVENT_SELECT,
    SECURE_INPUT_EVENT_BACK,

    SECURE_INPUT_EVENT_LOCK,
    SECURE_INPUT_EVENT_UNLOCK

} secure_input_event_t;

#endif
