#ifndef SECURE_UI_TYPES_H
#define SECURE_UI_TYPES_H

#include <stdint.h>
#include <stdbool.h>

typedef enum {
    SECURE_UI_SCREEN_BOOT = 0,
    SECURE_UI_SCREEN_LOCKED,
    SECURE_UI_SCREEN_AUTH,
    SECURE_UI_SCREEN_HOME,
    SECURE_UI_SCREEN_CONFIRM,
    SECURE_UI_SCREEN_ERROR,
    SECURE_UI_SCREEN_SHUTDOWN
} secure_ui_screen_t;

typedef enum {
    SECURE_UI_EVENT_NONE = 0,
    SECURE_UI_EVENT_BUTTON_UP,
    SECURE_UI_EVENT_BUTTON_DOWN,
    SECURE_UI_EVENT_BUTTON_SELECT,
    SECURE_UI_EVENT_TIMEOUT,
    SECURE_UI_EVENT_AUTH_SUCCESS,
    SECURE_UI_EVENT_AUTH_FAILURE
} secure_ui_event_t;

#endif
