#ifndef SECURE_UI_STATE_H
#define SECURE_UI_STATE_H

typedef enum {
    SECURE_SCREEN_BOOT = 0,
    SECURE_SCREEN_LOCKED,
    SECURE_SCREEN_AUTH,
    SECURE_SCREEN_HOME,
    SECURE_SCREEN_WARNING,
    SECURE_SCREEN_FIRMWARE_UPDATE
} secure_screen_t;

#endif
